### ISSUE TITLE
Add a middleware to protected routes

### ISSUE THREAD

**Issue by bonnieli** [ArtsyBiba/social_app#27]
Currently most routes require a user passed in to identify the user for example "http://localhost:5000/friends/usersList?currentUserId=601a2056abd2ac9e40eced4e" 

- The problem with this is that there's no protection 
- Since you verify the token, can pass in the JWT token every time identify the user instead of passing in the currentUserId every time, this would reduce a lot of code on the backend

It looks like you already have a middleware, but you don't currently utilize it in most places. The place that is used correctly is in your /delete user controller

**Comment by ArtsyBiba** [comment]
Completed
